name: Hello World Workflow

on: 
  push:   # Trigger on any push

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello Message
        run: echo "Hello CI/CD with GitHub Actions"
